version: '3.8'


services:
  samurai-app:
    container_name: samurai-app
    image: dleclercpro/samurai:external-network
    restart: always
    ports:
      - 80:80
    depends_on:
      - samurai-mongo
      - samurai-redis
    environment:
      NODE_ENV: local

  samurai-redis:
    container_name: samurai-redis
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  samurai-mongo:
    container_name: samurai-mongo
    image: mongo:4.4.4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./Apps/DatabaseApp/init.js:/docker-entrypoint-initdb.d/init.js:ro # Database initialization script
      - mongo:/data/db
    env_file:
      - .env.local


volumes:
  redis:
  mongo: