version: '3.8'


services:
  app:
    container_name: samurai-app
    image: dleclercpro/samurai:2.6.0
    restart: always
    depends_on:
      - redis
      - mongo
    environment:
      NODE_ENV: production

  nginx:
    container_name: samurai-nginx
    image: dleclercpro/ssl-reverse-proxy:latest
    restart: always
    ports:
      - 443:443 # HTTPS
      - 80:80   # HTTP
    volumes:
      - letsencrypt:/etc/letsencrypt # Keep SSL certificates
    depends_on:
      - app
    env_file:
      - .env.production

  redis:
    container_name: samurai-redis
    image: redis:6.2
    restart: always
    volumes:
      - redis:/data

  mongo:
    container_name: samurai-mongo
    image: mongo:4.4.4
    restart: always
    volumes:
      - ./Apps/DatabaseApp/init.js:/docker-entrypoint-initdb.d/init.js:ro # Database initialization script
      - mongo:/data/db
    env_file:
      - .env.production


volumes:
  redis:
  mongo:
  letsencrypt: