version: '3.8'


services:
  app:
    container_name: samurai-app
    image: dleclercpro/samurai-app:latest
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - mongo
      - redis
    environment:
      NODE_ENV: local

  redis:
    container_name: samurai-redis
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  mongo:
    container_name: samurai-mongo
    image: mongo:4.4.4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./Apps/DatabaseApp/conf:/docker-entrypoint-initdb.d:ro
      - mongo:/data/db
    env_file:
      - .env.local


volumes:
  redis:
  mongo: