version: '3.8'


services:
  app:
    container_name: samurai-app
    image: dleclercpro/samurai-app:latest
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - redis
      - mongo
    environment:
      NODE_ENV: production

  nginx:
    container_name: samurai-nginx
    image: dleclercpro/samurai-nginx:latest
    restart: always
    ports:
      - 443:443 # HTTPS
      - 80:80   # HTTP
    volumes:
      - ./Apps/ReverseProxy/conf/nginx.init.conf:/etc/nginx/nginx.init.conf:ro
      - ./Apps/ReverseProxy/conf/nginx.template.conf:/etc/nginx/nginx.template.conf:ro
      - letsencrypt:/etc/letsencrypt # Keep SSL certificates
      - webroot:/var/www/html
    depends_on:
      - app
    env_file:
      - .env.production

  redis:
    container_name: samurai-redis
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  mongo:
    container_name: samurai-mongo
    image: mongo:4.4.4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
      - ./Data/MongoDB/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}


volumes:
  redis:
  mongo:
  letsencrypt:
  webroot: