version: '3.8'


services:
  samurai-app:
    container_name: samurai-app
    image: dleclercpro/samurai:latest
    restart: always
    depends_on:
      - samurai-redis
      - samurai-mongo
    environment:
      NODE_ENV: production

  samurai-nginx:
    container_name: samurai-nginx
    image: dleclercpro/ssl-reverse-proxy:latest
    restart: always
    # ports:
      # - 443:443 # HTTPS
      # - 80:80   # HTTP
    volumes:
      - letsencrypt:/etc/letsencrypt # Keep SSL certificates
    depends_on:
      - samurai-app
    env_file:
      - .env.production

  samurai-redis:
    container_name: samurai-redis
    image: redis:6.2
    restart: always
    volumes:
      - redis:/data

  samurai-mongo:
    container_name: samurai-mongo
    image: mongo:4.4.4
    restart: always
    volumes:
      - ./Apps/DatabaseApp/init.js:/docker-entrypoint-initdb.d/init.js:ro # Database initialization script
      - mongo:/data/db
    env_file:
      - .env.production


volumes:
  redis:
  mongo:
  letsencrypt:


networks:
  default:
    external:
      name: router-network