version: '3.8'


services:
  samurai-app:
    container_name: samurai-app
    image: dleclercpro/samurai:external-network
    restart: always
    depends_on:
      - samurai-redis
      - samurai-mongo
    networks:
      - custom
    environment:
      NODE_ENV: production

  samurai-nginx:
    container_name: samurai-nginx
    image: dleclercpro/reverse-proxy:latest
    restart: always
    ports:      # Comment out when putting behind load balancer
      - 443:443 # HTTPS
      - 80:80   # HTTP
    networks:
      - custom
    volumes:
      - letsencrypt:/etc/letsencrypt # Keep SSL certificates
      - dhparams:/usr/dhparams       # Keep Dh params file
    depends_on:
      - samurai-app
    env_file:
      - .env.production

  samurai-redis:
    container_name: samurai-redis
    image: redis:6.2
    restart: always
    networks:
      - custom
    volumes:
      - redis:/data

  samurai-mongo:
    container_name: samurai-mongo
    image: mongo:4.4.4
    restart: always
    networks:
      - custom
    volumes:
      - ./Apps/DatabaseApp/init.js:/docker-entrypoint-initdb.d/init.js:ro # Database initialization script
      - mongo:/data/db
    env_file:
      - .env.production


volumes:
  redis:
  mongo:
  letsencrypt:
  dhparams:


networks:
  # Custom network to communicate with external services/containers
  custom:
    external: true