version: '3.8'

services:
  app:
    container_name: samurai-app
    image: samurai/app
    build:
      context: ./Apps
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - app
    depends_on:
      - mongo
      - redis
    environment:
      NODE_ENV: local

  redis:
    container_name: samurai-redis
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379
    networks:
      - app
    volumes:
      - redis:/data

  mongo:
    container_name: samurai-mongo
    image: mongo:4.4.4
    restart: always
    ports:
      - 27017:27017
    networks:
      - app
    volumes:
      - mongo:/data/db
      - ./Data/MongoDB/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

networks:
  app:
    driver: bridge

volumes:
  redis:
  mongo: