version: '3.8'


services:
  app:
    container_name: samurai-app
    image: dleclercpro/samurai:latest
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - redis
      - mongo
    environment:
      NODE_ENV: production

  redis:
    container_name: samurai-redis
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  mongo:
    container_name: samurai-mongo
    image: mongo:4.4.4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
      - ./Data/MongoDB/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

  nginx:
    image: nginx:latest
    ports:
      - 443:443 # HTTPS
      - 80:80   # HTTP
    volumes:
      - ./Data/NGINX/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-certs:/etc/nginx/certs:ro
    depends_on:
      - app  # Corrected indentation here

  certbot:
    image: certbot/certbot:latest
    volumes:
      - nginx-certs:/etc/letsencrypt
      - certbot-temp:/var/www/html # Temporary directory used during issuance of certificates
    command: certonly --webroot --webroot-path=/var/www/html -d ${DOMAIN} -d ${WWW_DOMAIN}
    depends_on:
      - nginx


volumes:
  redis:
  mongo:
  nginx-certs:
  certbot-temp: