export enum DialogType {
    Success = 'success',
    Error = 'error',
    SignIn = 'sign-in',
    SignUp = 'sign-up',
    PlayGame = 'play-game',
    CreateGame = 'create-game',
    GameOver = 'game-over',
    TileChoice = 'tile-choice',
    CasteChoice = 'caste-choice',
    TileMoveStart = 'tile-move-start',
    TileMoveEnd = 'tile-move-end',
    CasteSwitchStart = 'caste-switch-start',
    CasteSwitchEnd = 'caste-switch-confirm',
}