export enum DialogType {
    Success = 'success',
    Error = 'error',
    SetUser = 'sign-in',
    SignUp = 'sign-up',
    PlayGame = 'play-game',
    CreateGame = 'create-game',
    GameOver = 'game-over',
    NewTurn = 'new-turn',
    TileChoice = 'tile-choice',
    CasteChoice = 'caste-choice',
    TileMoveStart = 'tile-move-start',
    TileMoveEnd = 'tile-move-end',
    CasteSwapStart = 'caste-swap-start',
    CasteSwapEnd = 'caste-swap-confirm',
}